public class ErrorCatch {

	public static void test1() {
		class A {
			String a;
			int b;
		}
		A a = new A();
		A b;
		A c = new A();
		b = a;
		System.out.println(Integer.toHexString(a.hashCode()));
		System.out.println(Integer.toHexString(b.hashCode()));
		System.out.println(c.toString());
		System.out.println(a.equals(b));
		System.out.println(b.equals(a));
		System.out.println(b.equals(c));
	}

	public static void test2() {
		String data = null;
		try {
			System.out.println(data.toString());
		} catch (NullPointerException e) {
			System.out.println("널널널");
			System.out.println(e.getMessage());
		} finally {
			System.out.println("다시 실행하세요");
		}
	}

	public static void test3() {
		int[] a = new int[5];
		try {
			for (int i = 0; i < 6; i++) {
				a[i] = i;
			}
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("인덱스 초과");
		} finally {
			System.out.println("다시 실행하세요.");
		}
	}

	public static void main(String[] args) {
		test2();
	}
}
